package com.leapandbound.roommessage;

/**
 * Who wrote a chat message.
 *
 *   USER — a normal message typed by a member of the room.
 *   AI   — a reply generated by the Gemini AI assistant (posted when someone uses
 *          the "/ai <question>" command). AI messages have no human author, so their
 *          RoomMessage.userId is null.
 *
 * We persist the enum by NAME (its constant, e.g. 'AI') via @Enumerated(EnumType.STRING)
 * on the entity — the same convention {@link com.leapandbound.room.RoomStatus} and
 * {@link com.leapandbound.roomtimer.RoomTimerState} already use. Storing the name (not
 * the ordinal number) means reordering or adding constants later can't silently corrupt
 * existing rows.
 */
public enum SenderType {
    USER, AI
}
